# Generated by Django 5.2.7 on 2025-11-28 03:02

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('pierna', 'Pierna'), ('gluteo', 'Glúteo'), ('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('brazos', 'Brazos'), ('abdomen', 'Abdomen'), ('cuerpo_completo', 'Cuerpo Completo')], max_length=50)),
                ('secondary_muscles', models.JSONField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('equipment', models.CharField(choices=[('mancuernas', 'Mancuernas'), ('cuerpo', 'Sólo mi cuerpo'), ('bandas', 'Bandas de resistencia'), ('gimnasio', 'Máquinas de gimnasio')], max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen ejemplo', max_length=255, null=True, verbose_name='exercise_image')),
                ('ideal_angles', models.JSONField()),
                ('common_mistakes', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-created_at'],
            },
        ),
    ]
